### ISSUE TITLE
[QUESTION] How to use without need of sequential data

### ISSUE THREAD

**Issue by f-liva** [DarkGhostHunter/Laralocker#3]
I'm trying to use the package to avoid competition in Eloquent's **updateOrCreate** operations.

I'm obliged to implement the **startFrom** and **next** methods, which, however, are not necessary for my purpose, because all jobs are independent and there is no data to share between jobs.

How should I then implement these two methods to simply get a management of the competition when writing to the database?

**Comment by DarkGhostHunter** [comment]
> all jobs are independent and there is no data to share between jobs

If there is no data to share between jobs, then there is no need to use this package since there is no race condition. In other words, if the Job cannot know which "slot" in the locker is free, and from where in line, then it won't know what to occupy.

You may share the redacted code to check if there is a solution to your problem.

**Comment by f-liva** [comment]
I currently `return uniqid()` in both **startFrom** and **next**.

The jobs are concurrent, an `updateOrCreate` is performed on the same table and, if not managed with yout package, the competitiveness raises many duplicate key errors.

Is my approach correct?

**Comment by DarkGhostHunter** [comment]
Yes. the `startFrom()` is the starting point, like an ID from the database. This allows the Locker to not start from the very beginning. 

`next()` should return the next ID to "reserve". You can do anything there, like checking if the next ID is already taken or not in the database.
